### PR TITLE
grabbing hostgroup_title instead of hostgroup_name... 

### PR DESCRIPTION
**Pull request by smnmtzgr**
to return nested hostgroups to ansible

### CODE REVIEW

**Comment by agx** [comment]
We only want to use _title for the hostgroups not for organizations, etc. Can you respin it? Otherwise I can fix it.

**Comment by smnmtzgr** [comment]
changed this. please check.

**Comment by agx** [comment]
See my https://github.com/theforeman/foreman_ansible_inventory/pull/39 that handles old and new versions

**Comment by smnmtzgr** [comment]
done, please check again.

**Comment by smnmtzgr** [comment]
squashed into one commit. Please check if this is okay.

**Review by agx — APPROVED** [review]

**Comment by agx** [comment]
Thanks @smnmtzgr

**Comment by agx** [comment]
On Fri, Oct 14, 2016 at 11:23:00AM -0700, Simon wrote:

> squashed into one commit. Please check if this is okay.

Merged. Thans!

**Pull request merged**
