### PR TITLE
read foreman.ini from environment if set

### PR DESCRIPTION
**Pull request by wwitzel3**
Allow for reading foreman.ini from the environment.

### CODE REVIEW

**Comment by agx** [comment]
We should only add this to the list of config files if the env var is actually set otherwise:

> os.path.expanduser(os.path.expandvars(os.environ.get('FOREMAN_INI_PATH')))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/posixpath.py", line 287, in expandvars
>     if '$' not in path:
> TypeError: argument of type 'NoneType' is not iterable

**Comment by wwitzel3** [comment]
Thank you, fixed.

**Comment by dLobatog** [comment]
@wwitzel3 Thanks for the contribution. It looks good to me, can you add info on how to use it to the README? Ready to merge after that unless @agx has any qualms

**Comment by agx** [comment]
On Tue, Apr 12, 2016 at 12:17:33PM -0700, Daniel Lobato García wrote:

> @wwitzel3 Thanks for the contribution. It looks good to me, can you add info on how to use it to the README? Ready to merge after that unless @agx has any qualms

No objections, some info in README wold be awesome though.

**Comment by wwitzel3** [comment]
Is that README update good? Thanks.

**Comment by agx** [comment]
On Wed, Apr 13, 2016 at 09:00:16AM -0700, Wayne Witzel III wrote:

> Is that README update good? Thanks.

Merged now. Thanks!
 -- Guido

**Pull request merged**
